import { Inter } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import Sidebar from './components/sidebar/Sidebar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'RoamEpic',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Navbar /> */}
      <body className={inter.className}>
        {children}
      </body>
      {/* <div
          className='flex flex-row w-full h-full'
          >
        </div> */}
      {/* <Sidebar /> */}
    </html>
  )
}
